webtalk_init -webtalk_dir V:\\software\\m3_for_arty_a7\\sdk_workspace\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-06-11 13:35:29" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212246019_0_0_934" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ndf6dahoafggi7kbb6kslgif98" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.384 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1654933846058" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key Device -value "7a35ti" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1654933846058"
webtalk_add_data -client sdk -key uid -value "1654933857603" -context "sdk\\\\bsp/1654933857603"
webtalk_add_data -client sdk -key hwid -value "1654933846058" -context "sdk\\\\bsp/1654933857603"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1654933857603"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1654933857603"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1654933857603"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1654934729957"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1654934729957"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1654934729957"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1654934729957"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1654934729957"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1654934729957"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1654934729957"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1654934729957"
webtalk_transmit -clientid 2506627341 -regid "212246019_0_0_934" -xml V:\\software\\m3_for_arty_a7\\sdk_workspace\\webtalk\\usage_statistics_ext_sdk.xml -html V:\\software\\m3_for_arty_a7\\sdk_workspace\\webtalk\\usage_statistics_ext_sdk.html -wdm V:\\software\\m3_for_arty_a7\\sdk_workspace\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
